In [1]:
import numpy as np

In [7]:
#return array with 10 zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
#return array with 10 fives
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [10]:
#return array with values from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [18]:
#np.matrix('0 1 2; 3 4 5; 6 7 8')
#or 
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
#return unit matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
#return array 10x10 from 0.01 to 1
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [24]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [58]:
#return MxM matrix,sum,avg and sum of each column
m = np.random.randint(1,25,size=(5,5))
print(m)
print("Sum of all values:",m.sum())
print("Avarage of all values:",m.mean())
list = []
col1 = m[:,0].sum()
col2 = m[:,1].sum()
col3 = m[:,2].sum()
col4 = m[:,3].sum()
col5 = m[:,4].sum()
list = col1,col2,col3,col4,col5
print('Sum of every column:',list)

#or

m.sum(0)


[[16 21 16 19  3]
 [ 3  5  9 24  6]
 [ 3 11 11  6  2]
 [15  9  4  7 14]
 [24 12 11 23 13]]
Sum of every column: (61, 58, 51, 79, 38)


array([61, 58, 51, 79, 38])

In [75]:
#return MxM matrix and their min,max,median
m = np.random.randint(0,101,size=(5,5))
print(m)
print('Median value:',np.median(m))
print('Min value:',m.min())
print('Max value:',m.max())

[[ 12  57  92   2  67]
 [ 87  53  27  52  58]
 [ 64  81  21  27  41]
 [ 94  80  44  86 100]
 [ 59  81  77   4  65]]
Median value: 59.0
Min value: 2
Max value: 100


In [72]:
#return transposed  MxN matrix
m = np.random.randint(0,101,size=(2,4))
print(m)
print('Transposed matrix:',m.transpose())

[[ 8 58 96 80]
 [24  8 29 96]]
Transposed matrix: [[ 8 24]
 [58  8]
 [96 29]
 [80 96]]
